config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  root 'welcome#index'
  
  get 'my_news', to: 'users#my_news'
  get 'search_headlines', to: 'headlines#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/headline.rb
class Headline < ApplicationRecord
    
        def self.new_from_lookup(news_ticker)
            begin
                n = News.new(ENV['API_KEY'])
                n.get_top_headlines(sources: news_ticker)
            rescue Exception => e
                return nil
            end
        end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/headlines_controller.rb
class HeadlinesController < ApplicationController
    
   def search
      if params[:headline].present?
        @headline = Headline.new_from_lookup(params[:headline]).as_json
          if @headline
            render 'users/my_news'
          else
            flash[:danger] = "You have entered an incorrect News ticker"
            redirect_to my_news_path
          end
      else
        flash[:danger] = "You have entered an empty search string"
        redirect_to my_news_path
      end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
   def my_news
       
       
   end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
   def index
   
   
   end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "NewsApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->


    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">NewsApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Top Headlines", "/my_news"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/_result.html.erb
<% if @headline %>
    <div class="well results-block"> 
        
        
        <strong>Description: </strong><%= @id %>
    </div>
<% end %>

app/views/users/my_news.html.erb
<h1>My News </h1>

<h3>Top Headlines</h3>
<div id="headline-lookup">
  <%= form_tag search_headlines_path, method: :get, id: "headline-lookup-form" do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :headline, params[:headline], 
                                  placeholder: "News Ticker", autofocus: true,
                                  class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <i class="fa fa-search"></i> Top Headlines
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<% if @headline %>
    <div class="well results-block">
        <div class="col-md-12">
          <h4><u>Headlines:</u></h4>
          <% for i in 0..@headline.length-1 do %>
              <strong>(<%= i+1 %>) Title: </strong><%= @headline[i]["title"] %><br>
              <strong>Author: </strong><%= @headline[i]["author"] %></br>
              <strong>Description: </strong><%= @headline[i]["description"] %></br>
              <strong>URL: </strong><%= @headline[i]["url"] %></br><br>
          <% end %>
        </div> 
    </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to the News App</h1>

<%= link_to "logout", destroy_user_session_path, method: :delete %>